### PR TITLE
Prevent only one score on a pairing being set

### LINKED ISSUE #136: Seattle CO Tournament failed to generate pairings for fourth round
https://cobr.ai/tournaments/2988
Contact `@Whiteblade111#5606` or `@Maninthemoon(Abraham)#8507` on Discord for additional details.

### PR DESCRIPTION
**Pull request by haradan**
Resolves #136

### CODE REVIEW

File: app/models/pairing.rb [hunk 1]
```diff
@@ -85,6 +85,16 @@ def side_for(player)
   private
 
   def aggregate_scores
```
Comment (plural) [inline app/models/pairing.rb:87]: Does this PR also need something to ensure that 0 is recorded in the DB when scores are saved?

**Review by plural — APPROVED** [review]
This seems likely to fix the issue, but I’d prefer the bad data not be entered in the first place.

File: app/models/pairing.rb (hunk 1 above)
Comment (haradan) [reply app/models/pairing.rb:87]: I'm not sure what you mean. It looks like this is the method that did that already. It's set as a before save action. Do you think that's not enough? Maybe it could do with a better name, or some direct unit tests?

Comment (plural) [reply app/models/pairing.rb:87]: Oh!  I thought from the name of the function that this was used in calculating new pairings.  I clearly didn’t read carefully enough. Thanks for setting me straight.

This method is poorly named, for sure, but we can solve that later.

Does this still do the trick if you move this block after the `return unless`?  That seems a bit nicer since it won’t make any changes at all for that case.

Comment (haradan) [reply app/models/pairing.rb]: I've refactored the method, how does it look now?

File: app/models/pairing.rb [hunk 2]
```diff
@@ -84,11 +84,29 @@ def side_for(player)
 
   private
 
-  def aggregate_scores
-    return unless (score1_corp.present? && score1_corp > 0) || (score1_runner.present? && score1_runner > 0) ||
-      (score2_corp.present? && score2_corp > 0) || (score2_runner.present? && score2_runner > 0)
+  def prepare_scores_before_save
```
Comment (plural) [inline app/models/pairing.rb:87]: Looks great! Consider “normalize_scores” as an alternate method name, but it’s up to you.

**Review by plural — APPROVED** [review]
